isremote: true
mode: debug
nacos:
    clientconfig:
        appname: common.op.demo.microserver
        namespaceid: f9341555-a32d-492b-a604-611fb379e588
        password: 123456
        username: dev_common_op_demo
    serverconfigs:
        - grpcport: 9848
          ipaddr: 192.168.97.71
          port: 8848
    service:
        clustername: dev01
        enable: true
        ephemeral: true
        groupname: OP
        healthy: true
        port: 58651
        servicename: common.op.demo.microserver
        weight: 1
        others:
          - groupname: COMMON
            servicename: common.op.demo.log
          - groupname: COMMON
            servicename: common.op.demo.auth

