isRemote: true
nacos:
  Service:
   ClusterName: dev02
   ServiceName: party.op.norgannon
   GroupName:  PARTY
   Weight: 1
   IP:
   Port: 8080
   Ephemeral: false
   Enable: true
   Healthy: true
  ServerConfigs: 
   - 
     IpAddr: 192.168.97.71
     Port: 8848
     GrpcPort: 9848
  ClientConfig:
    NamespaceId: f9341555-a32d-492b-a604-611fb379e588
    AppName:     party.op.norgannon
    Username:    dev_party_op_norgannon
    Password:    123456

